### ISSUE TITLE
貌似失效了？

### ISSUE THREAD

**Issue by liuyib** [zouhangwithsweet/fubukicss-tool#11]
各位还能用吗？我这边已经没了，被 Figma 屏蔽了吗？

**Comment by liuyib** [comment]
![image](https://github.com/zouhangwithsweet/fubukicss-tool/assets/38221479/506c791d-3a9b-4e2a-9012-6a7573ff1ff5)

这个悬浮框在我这都没了

**Comment by Keytom27** [comment]
我这装好后，就没有这个悬浮窗...

**Comment by zouhangwithsweet** [comment]
对，只有购买了 dev mode 的用户才可以使用了！**Figma 已经在非付费的情况下，移除了插件依赖的API!**

**Comment by liuyib** [comment]
> 对，只有购买了 dev mode 的用户才可以使用了！**Figma 已经在非付费的情况下，移除了插件依赖的API!**

估计官方已经感知到了，gg

**Comment by JasonBoy** [comment]
也没了，刚要开发需求。。。

**Comment by Lstoryc** [comment]
+1 安装后无效果了

**Comment by zouhangwithsweet** [comment]
xdm！再坚持几天！
![image](https://github.com/zouhangwithsweet/fubukicss-tool/assets/21095710/f7b350e4-f55d-4f26-b580-2cc6e9ae7923)

**Comment by sukeshpabolu** [comment]
any update on this?

**Comment by zouhangwithsweet** [comment]
Just waiting figma rollback the api in `coming weeks`

**Comment by zouhangwithsweet** [comment]
截止目前，我们可以使用 "Duplicate to your drafts"，复制一份设计稿，进入编辑模式来使用本插件。但是我相信，Figma 既然做出了 API 回滚的承诺，这个插件应该会恢复正常的使用模式。

<img width="379" alt="image" src="https://github.com/zouhangwithsweet/fubukicss-tool/assets/21095710/c5f0368e-9fdb-462f-8ec5-0f7c438e452b">

**Comment by sukeshpabolu** [comment]
sadly I dont have copy permission. 😥

**Comment by geekris1** [comment]
The wait is long 😢

**Comment by DINLiang** [comment]
> 也没了，刚要开发需求。。。

你现在怎么开发啊 纯手写吗？

**Comment by zouhangwithsweet** [comment]
> > 也没了，刚要开发需求。。。
> 
> 
> 
> 你现在怎么开发啊 纯手写吗？

参考 readme 里边的操作

**Comment by wenyuanw** [comment]
> 截止目前，我们可以使用 "Duplicate to your drafts"，复制一份设计稿，进入编辑模式来使用本插件。但是我相信，Figma 既然做出了 API 回滚的承诺，这个插件应该会恢复正常的使用模式。
> 
> <img alt="image" width="379" src="https://private-user-images.githubusercontent.com/21095710/315317346-c5f0368e-9fdb-462f-8ec5-0f7c438e452b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzA4MzEsIm5iZiI6MTcxNTMzMDUzMSwicGF0aCI6Ii8yMTA5NTcxMC8zMTUzMTczNDYtYzVmMDM2OGUtOWZkYi00NjJmLThlYzUtMGY3YzQzOGU0NTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA4NDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzg3NjkyZDAwN2UwZDI5NmU2MjAyOWFjNjg1OWYwZGM4MjZiYTZhMTY3Y2UxZjMwODkzN2Y1NTQ1ZDcxOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rqRoXnbD2LDuTbqY8Ov6ff-6gAtBkT9fSEBqV53cikA">

好像目前编辑模式也不支持了

**Comment by zouhangwithsweet** [comment]
> > 截止目前，我们可以使用 "Duplicate to your drafts"，复制一份设计稿，进入编辑模式来使用本插件。但是我相信，Figma 既然做出了 API 回滚的承诺，这个插件应该会恢复正常的使用模式。
> > <img alt="image" width="379" src="https://private-user-images.githubusercontent.com/21095710/315317346-c5f0368e-9fdb-462f-8ec5-0f7c438e452b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzA4MzEsIm5iZiI6MTcxNTMzMDUzMSwicGF0aCI6Ii8yMTA5NTcxMC8zMTUzMTczNDYtYzVmMDM2OGUtOWZkYi00NjJmLThlYzUtMGY3YzQzOGU0NTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA4NDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzg3NjkyZDAwN2UwZDI5NmU2MjAyOWFjNjg1OWYwZGM4MjZiYTZhMTY3Y2UxZjMwODkzN2Y1NTQ1ZDcxOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rqRoXnbD2LDuTbqY8Ov6ff-6gAtBkT9fSEBqV53cikA">
> 
> 好像目前编辑模式也不支持了

https://github.com/zouhangwithsweet/fubukicss-tool/blob/main/entrypoints/content.ts#L4 matchs 支持一下就好
```ts
'https://www.figma.com/design/*'
```

**Comment by IcarusRyy** [comment]
> > > 截止目前，我们可以使用 "Duplicate to your drafts"，复制一份设计稿，进入编辑模式来使用本插件。但是我相信，Figma 既然做出了 API 回滚的承诺，这个插件应该会恢复正常的使用模式。
> > > <img alt="image" width="379" src="https://private-user-images.githubusercontent.com/21095710/315317346-c5f0368e-9fdb-462f-8ec5-0f7c438e452b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzA4MzEsIm5iZiI6MTcxNTMzMDUzMSwicGF0aCI6Ii8yMTA5NTcxMC8zMTUzMTczNDYtYzVmMDM2OGUtOWZkYi00NjJmLThlYzUtMGY3YzQzOGU0NTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA4NDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzg3NjkyZDAwN2UwZDI5NmU2MjAyOWFjNjg1OWYwZGM4MjZiYTZhMTY3Y2UxZjMwODkzN2Y1NTQ1ZDcxOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rqRoXnbD2LDuTbqY8Ov6ff-6gAtBkT9fSEBqV53cikA">
> > 
> > 
> > 好像目前编辑模式也不支持了
> 
> https://github.com/zouhangwithsweet/fubukicss-tool/blob/main/entrypoints/content.ts#L4 matchs 支持一下就好
> 
> ```ts
> 'https://www.figma.com/design/*'
> ```
> 
> 修复了，更新到最新即可

是不能使用了吗？ 安装了之后 在figma开发模式下，点击图标也没什么反应

**Comment by zouhangwithsweet** [comment]
> > > > 截止目前，我们可以使用 "Duplicate to your drafts"，复制一份设计稿，进入编辑模式来使用本插件。但是我相信，Figma 既然做出了 API 回滚的承诺，这个插件应该会恢复正常的使用模式。
> > > > <img alt="image" width="379" src="https://private-user-images.githubusercontent.com/21095710/315317346-c5f0368e-9fdb-462f-8ec5-0f7c438e452b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzA4MzEsIm5iZiI6MTcxNTMzMDUzMSwicGF0aCI6Ii8yMTA5NTcxMC8zMTUzMTczNDYtYzVmMDM2OGUtOWZkYi00NjJmLThlYzUtMGY3YzQzOGU0NTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA4NDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzg3NjkyZDAwN2UwZDI5NmU2MjAyOWFjNjg1OWYwZGM4MjZiYTZhMTY3Y2UxZjMwODkzN2Y1NTQ1ZDcxOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rqRoXnbD2LDuTbqY8Ov6ff-6gAtBkT9fSEBqV53cikA">
> > > 
> > > 
> > > 好像目前编辑模式也不支持了
> > 
> > 
> > https://github.com/zouhangwithsweet/fubukicss-tool/blob/main/entrypoints/content.ts#L4 matchs 支持一下就好
> > ```ts
> > 'https://www.figma.com/design/*'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 修复了，更新到最新即可
> 
> 是不能使用了吗？ 安装了之后 在figma开发模式下，点击图标也没什么反应

本来就不能再 dev mode 下使用。

**Comment by IcarusRyy** [comment]
> > > > > 截止目前，我们可以“复制到您的草稿”，复制一份设计稿，进入编辑模式来使用本插件。但是我相信，Figma 既然做出了 API 承诺，这个插件应该会恢复正常的使用模式。
> > > > > <img alt="图像" width="379" src="https://private-user-images.githubusercontent.com/21095710/315317346-c5f0368e-9fdb-462f-8ec5-0f7c438e452b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzA4MzEsIm5iZiI6MTcxNTMzMDUzMSwicGF0aCI6Ii8yMTA5NTcxMC8zMTUzMTczNDYtYzVmMDM2OGUtOWZkYi00NjJmLThlYzUtMGY3YzQzOGU0NTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA4NDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzg3NjkyZDAwN2UwZDI5NmU2MjAyOWFjNjg1OWYwZGM4MjZiYTZhMTY3Y2UxZjMwODkzN2Y1NTQ1ZDcxOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rqRoXnbD2LDuTbqY8Ov6ff-6gAtBkT9fSEBqV53cikA">
> > > > 
> > > > 
> > > > 好像目前编辑模式也支持了
> > > 
> > > 
> > > https://github.com/zouhangwithsweet/fubukicss-tool/blob/main/entrypoints/content.ts#L4匹配 支持一下就好
> > > ```ts
> > > 'https://www.figma.com/design/*'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 修复了，更新到最新即可
> > 
> > 
> > 是否不能使用？ 答案： 相同 在 figma开发模式下，点击图标也没有任何反应
> 
> 本来就不能再在开发模式下使用。

目前应该怎么使用呢？ 在草稿环境 编辑模式 点击图标 也没有弹出。😭

**Comment by zouhangwithsweet** [comment]
不用点击图标，草稿模式下刷新页面就行，自动出现页面上。

**Comment by IcarusRyy** [comment]
> 不用点击图标，草稿模式下刷新页面就行，自动出现页面上。

![image](https://github.com/zouhangwithsweet/fubukicss-tool/assets/70784064/37904d36-c68c-485b-835b-e65a16194da9)
没显示呢。 在哪显示呀🥺

**Comment by zouhangwithsweet** [comment]
参考 readme 的方法

**Comment by IcarusRyy** [comment]
> 参考 readme 的方法

我现在就是草稿模式下的编辑模式🤦

**Comment by zouhangwithsweet** [comment]
你这个页面应该不是编辑模式，至少这个要关掉。
![image](https://github.com/zouhangwithsweet/fubukicss-tool/assets/21095710/fe552cb4-bc06-4d29-8709-a8c9078d0592)

**Comment by zouhangwithsweet** [comment]
fix with d8e92a45269bfaad1f0eda1b1169b56d1c801353

**Comment by bobsam** [comment]
Hello, 我这边的插件，现在无法使用了。Chrome 版本是：版本 135.0.7049.96（正式版本） (arm64)。请问 Figma 那边是有什么更新导致无法使用了吗？
