### ISSUE TITLE
Dark Mode 

### ISSUE THREAD

**Issue by AmrTamer23** [zouhangwithsweet/fubukicss-tool#13]
Thanks for the amazing tool, really needed it, but I'm kinda struggling with not having a dark mode for the extension.

If I can work on this let me know!

**Comment by zouhangwithsweet** [comment]
add dark theme for pannel. https://github.com/zouhangwithsweet/fubukicss-tool/commit/0a64fec151b1ab60d5f15d655434155bff4d1444

todo: dropdown menu support dark theme

**Comment by zouhangwithsweet** [comment]
![image](https://github.com/zouhangwithsweet/fubukicss-tool/assets/21095710/eab729e9-75f3-4a1b-9c8e-2d155f5fd7fc)

**Comment by AmrTamer23** [comment]
Got it, will do and submit a PR ASAP.
