### ISSUE TITLE
希望css的单位能按rem显示

### ISSUE THREAD

**Issue by abcdGJJ** [zouhangwithsweet/fubukicss-tool#9]
目前插件里选了rem，但是显示的仍然是px。期望能有一个类似于postcss设置rootValue的地方，自动将px转成rem显示

**Comment by zouhangwithsweet** [comment]
更推荐使用 atomic 去使用 rem，插件中的 CSS 本质上是就是展示原始数据。

**Comment by abcdGJJ** [comment]
> 更新：E0 老师新做的同类插件支持 px -> rem https://github.com/ecomfe/tempad-dev

👍🏻
